import localFont from "next/font/local";
import "./globals.css";

//components
import Header from "../components/Header";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-pretendard",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={pretendard.variable}>
        <Header></Header>

        {children}
      </body>
    </html>
  );
}
